import { getTemplateDefinition } from '../data/templateCatalog';

const SECTION_ORDER = [
  { key: 'reference_points', label: 'Reference Points' },
  { key: 'zones', label: 'Zones' },
  { key: 'sides', label: 'Side Postures' },
  { key: 'units', label: 'Units' },
  { key: 'loadouts', label: 'Loadouts' },
  { key: 'missions', label: 'Missions' },
  { key: 'kvstore', label: 'KeyValue Store' },
  { key: 'doctrines', label: 'Doctrines' },
  { key: 'emcon', label: 'EMCON' },
  { key: 'weather_blocks', label: 'Weather Blocks' },
  { key: 'events', label: 'Events' },
];

function luaQuote(value) {
  const text = String(value ?? '');
  if (text.includes('\n')) {
    return `[=[${text}]=]`;
  }

  return `"${text.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
}

function serializeValue(value, field) {
  if (value === undefined || value === null || value === '') {
    return null;
  }

  if (field?.type === 'lua') {
    return String(value).trim();
  }

  if (field?.type === 'number') {
    return Number.isFinite(Number(value)) ? String(Number(value)) : null;
  }

  if (field?.type === 'checkbox') {
    return value ? 'true' : 'false';
  }

  if (typeof value === 'boolean') {
    return value ? 'true' : 'false';
  }

  if (typeof value === 'number') {
    return String(value);
  }

  return luaQuote(value);
}

function entryToLua(event) {
  const definition = getTemplateDefinition(event.kind);
  const section = definition.presetSection || 'events';
  const lines = ['        {'];

  if (definition.includeName !== false && event.name) {
    lines.push(`            name = ${luaQuote(event.name)},`);
  }

  if (section === 'events') {
    lines.push(`            kind = ${luaQuote(definition.outputKind || event.kind)},`);
  } else if (definition.outputKind) {
    lines.push(`            kind = ${luaQuote(definition.outputKind)},`);
  }

  Object.entries(definition.staticFields || {}).forEach(([key, value]) => {
    lines.push(`            ${key} = ${serializeValue(value)},`);
  });

  definition.fields.forEach((field) => {
    if (field.output === false) return;
    if (field.visibleWhen && !field.visibleWhen(event)) return;

    const serialized = serializeValue(event[field.name], field);
    if (serialized !== null) {
      lines.push(`            ${field.outputName || field.name} = ${serialized},`);
    }
  });

  lines.push('        }');
  return lines.join('\n');
}

function sectionToLua(section, entries) {
  if (!entries?.length) return null;

  return `    -- ----- ${section.label} -----
    ${section.key} = {
${entries.join(',\n')}
    },`;
}

export function generatePresetLua(events, settings = {}) {
  const groups = events.reduce((accumulator, event) => {
    const definition = getTemplateDefinition(event.kind);
    const section = definition.presetSection || 'events';
    accumulator[section] ||= [];
    accumulator[section].push(entryToLua(event));
    return accumulator;
  }, {});
  const multiFile = settings.multi_file ? 'true' : 'false';
  const outNameLine = settings.multi_file ? `    out_name = ${luaQuote(settings.out_name || 'ui_generated_pack')},\n` : '';
  const sectionBlocks = SECTION_ORDER
    .map((section) => sectionToLua(section, groups[section.key]))
    .filter(Boolean);

  return `return {
    header = {
        title = ${luaQuote(settings.title || 'CMO Lua UI Preset')},
        description = ${luaQuote(settings.description || 'Generated by cmo-lua-ui')}
    },
    multi_file = ${multiFile},
${outNameLine}    allow_invalid_dbids = ${settings.allow_invalid_dbids ? 'true' : 'false'},

${sectionBlocks.length ? sectionBlocks.join('\n\n') : '    -- Add Builder forms in the left panel.'}
}
`;
}
