local function ReturnPlayerSide()
	local result = VP_GetSide({side='playerside'}).name
	return result
end

local playerSide = ReturnPlayerSide()

if playerSide == 'Israel' then
	ScenEdit_SetEvent('Leading to hostility',{isactive=true})
	ScenEdit_SetEvent('Syrian Air Defense HQ is out of action2',{isactive=true})
	ScenEdit_SetEvent('Leading to hostility2',{isactive=false})
	ScenEdit_SetSidePosture('Israel', 'Syria', 'U')
	ScenEdit_SetSidePosture('Israel', 'Syria.', 'U')
	ScenEdit_SetSidePosture('Israel', 'Iranian Infrastructure', 'U')
	ScenEdit_SetUnit( {side = 'Syria', unitname = "Buk-M2E (T4) #5", autodetectable="False"} )
	ScenEdit_SetUnit( {side = 'Syria', unitname = "SAM Bn S-300PMU-2 (T4) #3", autodetectable="False"} )
	ScenEdit_SetUnit( {side = 'Syria', unitname = "Pantsir-S1E (T4) #25", autodetectable="False"} )
	ScenEdit_SetUnit( {side = 'Syria', unitname = "Pantsir-S1E (T4) #26", autodetectable="False"} )
	ScenEdit_SetUnit( {side = 'Syria', unitname = "Pantsir-S1E (T4) #27", autodetectable="False"} )
	ScenEdit_SetUnit( {side = 'Syria', unitname = "Radar 9S36 #1", autodetectable="False"} )
	ScenEdit_SetUnit( {side = 'Syria', unitname = "SAM Bn S-300PMU-2 (Damascus East) #1", autodetectable="False"} )
	ScenEdit_SetUnit( {side = 'Syria', unitname = "Pantsir-S1E (Damascus East) #12", autodetectable="False"} )
	ScenEdit_SetUnit( {side = 'Syria', unitname = "Pantsir-S1E (Damascus East) #13", autodetectable="False"} )
	ScenEdit_SetUnit( {side = 'Syria', unitname = "Buk-M2E (Damascus East) #1", autodetectable="False"} )
	ScenEdit_SetUnit( {side = 'Syria', unitname = "Radar 64N6 #1", autodetectable="False"} )
	ScenEdit_SetUnit( {side = 'Syria', unitname = "Radar 9S36 #3", autodetectable="False"} )
	ScenEdit_SetUnit( {side = 'Syria', unitname = "SAM Bn S-300PMU-2 (Damascus North) #2", autodetectable="False"} )
	ScenEdit_SetUnit( {side = 'Syria', unitname = "Buk-M2E (Damascus North) #2", autodetectable="False"} )
	ScenEdit_SetUnit( {side = 'Syria', unitname = "Buk-M2E (Damascus North) #3", autodetectable="False"} )
	ScenEdit_SetUnit( {side = 'Syria', unitname = "Syrian Air Defense HQ", autodetectable="False"} )
	ScenEdit_SetUnit( {side = 'Syria', unitname = "Pantsir-S1E #10", autodetectable="False"} )
	ScenEdit_SetUnit( {side = 'Syria', unitname = "SAM Bn S-125M (Damascus West) #3", autodetectable="False"} )
	ScenEdit_SetUnit( {side = 'Syria', unitname = "SAM Bn S-125M (Damascus West) #4", autodetectable="False"} )
	ScenEdit_SetUnit( {side = 'Syria', unitname = "SAM Bn 2K12E Kvadrat (Damascus West) #7", autodetectable="False"} )
	ScenEdit_SetUnit( {side = 'Syria', unitname = "Buk-M1 (Damascus West) #2", autodetectable="False"} )
	ScenEdit_SetUnit( {side = 'Syria', unitname = "Pantsir-S1E (Damascus West) #22", autodetectable="False"} )
	ScenEdit_SetUnit( {side = 'Syria', unitname = "Pantsir-S1E (Damascus West) #23", autodetectable="False"} )
	ScenEdit_SetUnit( {side = 'Syria', unitname = "SAM Bn 2K12E Kvadrat #3", autodetectable="False"} )
	ScenEdit_SetUnit( {side = 'Syria', unitname = "Mobile Sector Control - IADS South Syria", autodetectable="False"} )
	ScenEdit_SetUnit( {side = 'Syria', unitname = "Pantsir-S1E #3", autodetectable="False"} )
	ScenEdit_SetUnit( {side = 'Syria', unitname = "Pantsir-S1E #7", autodetectable="False"} )
	ScenEdit_SetUnit( {side = 'Syria', unitname = "Pantsir-S1E #2", autodetectable="False"} )
	ScenEdit_SetUnit( {side = 'Syria', unitname = "Pantsir-S1E #8", autodetectable="False"} )
	ScenEdit_SetUnit( {side = 'Syria', unitname = "Pantsir-S1E #11", autodetectable="False"} )
	local side = 'Israel'
	local listOfRPNames = {'RP-3055','RP-3056','RP-3057','RP-3057','RP-3058','RP-3022','RP-3023','RP-3024','RP-3025','RP-3027','RP-3028','RP-3029','RP-3030','RP-3033','RP-3034','RP-3035','RP-3036','RP-3038','RP-3039','RP-3040','RP-3041','RP-3042','RP-3043','RP-3044','RP-3045'}
	for k,v in ipairs (listOfRPNames) do
		ScenEdit_DeleteReferencePoint({name=v,side=side})
	end
	ScenEdit_DeleteMission('Israel','Strike Package Tango 03')
	ScenEdit_DeleteMission('Israel','Strike Package Echo 01')
	ScenEdit_DeleteMission('Israel','Strike Package Tango 02')
	ScenEdit_DeleteMission('Israel','Strike Package Tango 04')
	ScenEdit_DeleteMission('Israel','Strike Package Echo 03')
	ScenEdit_DeleteMission('Israel','Strike Package Echo 05')
	ScenEdit_DeleteMission('Israel','Strike Package Echo 04')
	ScenEdit_DeleteMission('Israel','Strike Package Foxtrot 02')
	ScenEdit_DeleteMission('Israel','Tanker Support 01')
	ScenEdit_DeleteMission('Israel','Tanker Support 02')
	ScenEdit_DeleteMission('Israel','Strike Package November 04')
	ScenEdit_DeleteMission('Israel','Strike Package Foxtrot 03')
	ScenEdit_DeleteMission('Israel','Strike Package November 07')
	ScenEdit_DeleteMission('Israel','Strike Package Tango 06')
	ScenEdit_DeleteMission('Israel','Strike Package Tango 05')
	ScenEdit_DeleteMission('Israel','Strike Package Echo 02')
	ScenEdit_DeleteMission('Israel','Strike Package November 05')
	ScenEdit_DeleteMission('Israel','Strike Package Tango 01')
	ScenEdit_DeleteMission('Israel','Strike Package November 02')
	ScenEdit_DeleteMission('Israel','Strike Package November 01')
	ScenEdit_DeleteMission('Israel','Strike Package November 06')
	ScenEdit_DeleteMission('Israel','Strike Package Foxtrot 01')
	ScenEdit_DeleteMission('Israel','Strike Package November 03')
	ScenEdit_DeleteMission('Israel','Strike Package Foxtrot 04')
	ScenEdit_DeleteMission('Israel','Hatzor AB')
	ScenEdit_DeleteMission('Israel','Hazerim AB')
	ScenEdit_DeleteMission('Israel','Nevatim AB')
	ScenEdit_DeleteMission('Israel','Ovda AB')
	ScenEdit_DeleteMission('Israel','Palmachim AB')
	ScenEdit_DeleteMission('Israel','Ramat David AB')
	ScenEdit_DeleteMission('Israel','Ramon AB')
	ScenEdit_DeleteMission('Israel','Tel Aviv-Dov Hoz AB')
	ScenEdit_DeleteMission('Israel','Tel Nof AB')
	ScenEdit_DeleteMission('Israel','LYNX Strike')
	ScenEdit_DeleteMission('Israel','M270 Strike')
end