import { lazy, Suspense, useEffect, useState } from 'react';
import { BookOpen, Bot, Settings2 } from 'lucide-react';
import FeaturePalette from './components/FeaturePalette';
import LuaAssistant from './components/LuaAssistant';
import { generatePresetLua } from './lib/presetLua';
import {
  FEATURE_FORM_GROUPS,
  createEventFromTemplate,
  getTemplateDefinition,
} from './data/templateCatalog';

const AiAdapterSettings = lazy(() => import('./components/AiAdapterSettings'));
const PresetGuide = lazy(() => import('./components/PresetGuide'));

const WORKSPACE_TABS = [
  { id: 'assistant', label: 'Event/Lua Assistant', icon: Bot, hint: 'CMO 코드 분석/수정' },
  { id: 'guide', label: 'Preset Guide', icon: BookOpen, hint: '프리셋 지침/예제' },
  { id: 'settings', label: 'Settings', icon: Settings2, hint: '화면/편집기 설정' },
];

const THEME_OPTIONS = [
  { id: 'command', label: 'Command' },
  { id: 'pacific', label: 'Pacific' },
  { id: 'sandtable', label: 'Sandtable' },
  { id: 'steel', label: 'Steel' },
  { id: 'dark', label: 'Dark' },
];

const THEME_STORAGE_KEY = 'cmo-lua-ui-theme';
const EDITOR_SETTINGS_STORAGE_KEY = 'cmo-lua-ui-editor-settings';
const WORKSPACE_STATE_STORAGE_KEY = 'cmo-lua-ui-workspace-state';
const CUSTOM_PRESET_STORAGE_KEY = 'cmo-lua-ui-custom-presets';

const EDITOR_FONT_OPTIONS = [
  { id: 'plex', label: 'IBM Plex Mono', family: 'IBM Plex Mono', value: "'IBM Plex Mono', Consolas, monospace" },
  { id: 'cascadia', label: 'Cascadia', family: 'Cascadia Code', families: ['Cascadia Code', 'Cascadia Mono'], value: "'Cascadia Code', 'Cascadia Mono', Consolas, monospace" },
  { id: 'consolas', label: 'Consolas', family: 'Consolas', value: "Consolas, 'Courier New', monospace" },
  { id: 'malgun', label: '맑은 고딕', family: 'Malgun Gothic', families: ['Malgun Gothic', '맑은 고딕'], value: "'Malgun Gothic', '맑은 고딕', sans-serif" },
  { id: 'gulim', label: '굴림', family: 'Gulim', families: ['Gulim', '굴림'], value: "Gulim, '굴림', sans-serif" },
  { id: 'dotum', label: '돋움', family: 'Dotum', families: ['Dotum', '돋움'], value: "Dotum, '돋움', sans-serif" },
  { id: 'batang', label: '바탕', family: 'Batang', families: ['Batang', '바탕'], value: "Batang, '바탕', serif" },
];

const DEFAULT_EDITOR_SETTINGS = {
  fontFamily: 'plex',
  fontSize: 15,
};

const DEFAULT_PRESET_SETTINGS = {
  title: 'CMO Lua UI Preset',
  description: 'Generated by cmo-lua-ui against current CMO Lua references',
  multi_file: true,
  out_name: 'ui_generated_pack',
  allow_invalid_dbids: false,
};

function readAssistantCustomPresets() {
  if (typeof window === 'undefined') return [];

  try {
    const parsed = JSON.parse(window.localStorage.getItem(CUSTOM_PRESET_STORAGE_KEY) || '[]');
    return Array.isArray(parsed) ? parsed.filter((preset) => Array.isArray(preset?.events) && preset.events.length) : [];
  } catch {
    return [];
  }
}

const SETTINGS_SECTIONS = [
  { id: 'interface', label: '인터페이스' },
  { id: 'storage', label: '저장 / Preset' },
  { id: 'ai', label: 'AI Adapter' },
];

function getInitialTheme() {
  if (typeof window === 'undefined') {
    return 'command';
  }

  const savedTheme = window.localStorage.getItem(THEME_STORAGE_KEY);
  return THEME_OPTIONS.some((option) => option.id === savedTheme) ? savedTheme : 'command';
}

function getInitialEditorSettings() {
  if (typeof window === 'undefined') {
    return DEFAULT_EDITOR_SETTINGS;
  }

  try {
    const savedSettings = JSON.parse(window.localStorage.getItem(EDITOR_SETTINGS_STORAGE_KEY) || '{}');
    const fontFamily = EDITOR_FONT_OPTIONS.some((option) => option.id === savedSettings.fontFamily)
      ? savedSettings.fontFamily
      : DEFAULT_EDITOR_SETTINGS.fontFamily;
    const fontSize = Number(savedSettings.fontSize);

    return {
      fontFamily,
      fontSize: Number.isFinite(fontSize) ? Math.min(Math.max(fontSize, 12), 22) : DEFAULT_EDITOR_SETTINGS.fontSize,
    };
  } catch {
    return DEFAULT_EDITOR_SETTINGS;
  }
}

function getDefaultWorkspaceState() {
  return {
    events: [createEventFromTemplate('iads_ambush')],
    activeTab: 'assistant',
    sidePaneWidth: 390,
    settings: DEFAULT_PRESET_SETTINGS,
  };
}

function getInitialWorkspaceState() {
  const fallback = getDefaultWorkspaceState();

  if (typeof window === 'undefined') {
    return fallback;
  }

  try {
    const savedState = JSON.parse(window.localStorage.getItem(WORKSPACE_STATE_STORAGE_KEY) || '{}');
    const savedSidePaneWidth = Number(savedState.sidePaneWidth);
    const legacyTabMap = {
      builder: 'guide',
      reference: 'guide',
      output: 'assistant',
    };
    const savedActiveTab = legacyTabMap[savedState.activeTab] || savedState.activeTab;
    const activeTab = WORKSPACE_TABS.some((tab) => tab.id === savedActiveTab)
      ? savedActiveTab
      : fallback.activeTab;

    return {
      events: Array.isArray(savedState.events) && savedState.events.length ? savedState.events : fallback.events,
      activeTab,
      sidePaneWidth: Number.isFinite(savedSidePaneWidth) ? Math.min(Math.max(savedSidePaneWidth, 300), 680) : fallback.sidePaneWidth,
      settings: { ...DEFAULT_PRESET_SETTINGS, ...(savedState.settings || {}) },
    };
  } catch {
    return fallback;
  }
}

function quoteFontFamily(family) {
  return family === 'ui-monospace' ? family : `"${family.replace(/"/g, '\\"')}"`;
}

function isEditorFontAvailable(option) {
  if (typeof document === 'undefined' || !document.fonts?.check) return true;
  return (option.families || [option.family]).some((family) => (
    document.fonts.check(`14px ${quoteFontFamily(family)}`)
  ));
}

function getAvailableEditorFonts() {
  const detectedFonts = EDITOR_FONT_OPTIONS.filter(isEditorFontAvailable);
  return detectedFonts.length
    ? detectedFonts
    : [EDITOR_FONT_OPTIONS.find((option) => option.id === 'consolas') || EDITOR_FONT_OPTIONS[0]];
}

function AppSettingsWorkspace({
  theme,
  setTheme,
  editorSettings,
  updateEditorSetting,
  availableEditorFonts,
  detectedFontCount,
  settings,
  updateSetting,
}) {
  const [activeSection, setActiveSection] = useState('interface');
  const [hasOpenedAiSettings, setHasOpenedAiSettings] = useState(activeSection === 'ai');
  const selectedFont = availableEditorFonts.find((option) => option.id === editorSettings.fontFamily)
    || availableEditorFonts[0]
    || EDITOR_FONT_OPTIONS[0];

  return (
    <section className="app-settings-workspace glass-panel">
      <div className="section-header">
        <div>
          <h2>Workspace Settings</h2>
        </div>
      </div>

      <div className="settings-section-tabs" aria-label="설정 항목">
        {SETTINGS_SECTIONS.map((section) => (
          <button
            key={section.id}
            className={activeSection === section.id ? 'active' : ''}
            type="button"
            onClick={() => {
              setActiveSection(section.id);
              if (section.id === 'ai') {
                setHasOpenedAiSettings(true);
              }
            }}
          >
            {section.label}
          </button>
        ))}
      </div>

      <div className="settings-workspace-body">
        {activeSection === 'interface' && (
          <div className="settings-panel-grid interface-settings-grid">
            <section className="interface-setting-group theme-interface-group">
              <div className="interface-group-title">
                <strong>Theme</strong>
                <span>전체 색상 테마</span>
              </div>
              <section className="settings-panel-card theme-settings-card">
                <label className="settings-select-row">
                  Theme
                  <select value={theme} onChange={(event) => setTheme(event.target.value)}>
                    {THEME_OPTIONS.map((option) => (
                      <option key={option.id} value={option.id}>{option.label}</option>
                    ))}
                  </select>
                </label>
                <div className="settings-current-note">
                  현재 테마: {THEME_OPTIONS.find((option) => option.id === theme)?.label || theme}
                </div>
              </section>
            </section>

            <section className="interface-setting-group typography-interface-group">
              <div className="interface-group-title">
                <strong>Font / Preview</strong>
                <span>Lua 편집기 표시</span>
              </div>
              <div className="typography-settings-grid">
                <section className="settings-panel-card font-settings-card">
                  <h3>Lua Editor Typography</h3>
                  <label>
                    Font
                    <select
                      className="font-family-select"
                      style={{ fontFamily: selectedFont.value }}
                      value={selectedFont.id}
                      onChange={(event) => updateEditorSetting('fontFamily', event.target.value)}
                    >
                      {availableEditorFonts.map((option) => (
                        <option key={option.id} value={option.id} style={{ fontFamily: option.value }}>
                          {option.label}
                        </option>
                      ))}
                    </select>
                  </label>
                  <div className="settings-current-note">
                    사용 가능 폰트: {availableEditorFonts.length}/{detectedFontCount}개
                  </div>
                  <label>
                    Font size
                    <div className="font-size-control">
                      <input
                        type="range"
                        min="12"
                        max="22"
                        value={editorSettings.fontSize}
                        onChange={(event) => updateEditorSetting('fontSize', Number(event.target.value))}
                      />
                      <output>{editorSettings.fontSize}px</output>
                    </div>
                  </label>
                </section>
                <section className="settings-panel-card editor-preview-card">
                  <h3>Preview</h3>
                  <pre style={{ fontFamily: selectedFont.value, fontSize: `${editorSettings.fontSize}px` }}>
{`local unit = ScenEdit_GetUnit({ name = "DDG 1000 Zumwalt" })
if unit ~= nil then
  ScenEdit_MsgBox("Lua editor preview")
end`}
                  </pre>
                </section>
              </div>
            </section>
          </div>
        )}

        {activeSection === 'storage' && (
          <div className="settings-panel-grid storage-settings-grid">
            <PresetSettings settings={settings} updateSetting={updateSetting} />
            <SidecarCacheSettings />
            <section className="settings-panel-card">
              <h3>Lua Bundle Save</h3>
              <p>묶음/폴더로 연 Lua는 Assistant 상단의 저장 버튼으로 상대경로 구조를 유지한 채 분리 저장할 수 있습니다.</p>
              <p>브라우저가 폴더 저장 API를 지원하지 않으면 각 파일을 개별 다운로드로 저장합니다.</p>
            </section>
          </div>
        )}

        {(activeSection === 'ai' || hasOpenedAiSettings) && (
          <div hidden={activeSection !== 'ai'}>
            <Suspense fallback={<div className="settings-panel-card">AI Adapter 설정을 불러오는 중입니다.</div>}>
              <AiAdapterSettings />
            </Suspense>
          </div>
        )}
      </div>
    </section>
  );
}

function SidecarCacheSettings() {
  const [cacheStatus, setCacheStatus] = useState({
    state: 'loading',
    message: 'scenario sidecar index를 확인하는 중입니다.',
    counts: {},
    total: 0,
  });

  useEffect(() => {
    let cancelled = false;

    async function loadIndex() {
      try {
        const response = await fetch('/scenario-sidecars/scenario-openability-index.json', { cache: 'no-store' });
        if (!response.ok) throw new Error(`HTTP ${response.status}`);
        const index = await response.json();
        if (cancelled) return;

        setCacheStatus({
          state: 'ok',
          message: `마지막 인덱스: ${index.generatedAt || 'unknown'}`,
          counts: index.counts || {},
          total: index.totalScenarios || index.scenarios?.length || 0,
        });
      } catch (error) {
        if (cancelled) return;
        setCacheStatus({
          state: 'error',
          message: `sidecar index를 읽지 못했습니다: ${error.message}`,
          counts: {},
          total: 0,
        });
      }
    }

    loadIndex();
    return () => {
      cancelled = true;
    };
  }, []);

  const copyCommand = async (command) => {
    try {
      await navigator.clipboard.writeText(command);
    } catch {
      // Clipboard can be blocked in some browsers. The command remains visible.
    }
  };

  const commandRows = [
    {
      label: '상태 점검',
      command: 'npm run audit:scenario-sidecars',
      note: '전체 JSON 캐시, 보호 파일, 고아 파일 용량을 dry-run으로 확인합니다.',
    },
    {
      label: '고아 캐시 확인',
      command: 'npm run prune:scenario-sidecars',
      note: '인덱스가 참조하지 않는 sidecar만 삭제 후보로 보여줍니다.',
    },
    {
      label: '고아 캐시 삭제',
      command: 'npm run prune:scenario-sidecars -- --yes',
      note: 'dry-run 확인 후 사용하세요. 원본 .scen은 수정하지 않고, 참조 중인 sidecar는 보호됩니다.',
    },
    {
      label: '외부 캐시 이전 확인',
      command: 'npm run move:scenario-sidecars',
      note: '기본 외부 캐시 위치로 옮길 수 있는지 dry-run으로 확인합니다.',
    },
    {
      label: '외부 캐시로 이동',
      command: 'npm run move:scenario-sidecars -- --move --yes',
      note: 'dry-run 확인 후 사용하세요. 이동 후에도 /scenario-sidecars URL로 자동 연결됩니다.',
    },
  ];

  return (
    <section className="settings-panel-card sidecar-cache-settings-card">
      <h3>Scenario Sidecar Cache</h3>
      <p>
        로컬 분석용 sidecar 캐시입니다. 원본 파일(.scen)은 절대 수정되지 않습니다.
      </p>
      <div className={`sidecar-cache-status ${cacheStatus.state}`}>
        <strong>{cacheStatus.total ? `${cacheStatus.total.toLocaleString()} scenarios indexed` : 'index pending'}</strong>
        <span>{cacheStatus.message}</span>
      </div>
      <div className="sidecar-cache-counts">
        <span><strong>{cacheStatus.counts.readyWithInternalSidecar || 0}</strong> ready</span>
        <span><strong>{cacheStatus.counts.metadataOnlyNeedsDecoder || 0}</strong> metadata</span>
        <span><strong>{cacheStatus.counts.decoderFailed || 0}</strong> failed</span>
      </div>
      <div className="sidecar-cache-command-list">
        {commandRows.map((row) => (
          <div className="sidecar-cache-command" key={row.command}>
            <div>
              <strong>{row.label}</strong>
              <code>{row.command}</code>
              <span>{row.note}</span>
            </div>
            <button className="btn btn-ghost" type="button" onClick={() => copyCommand(row.command)}>
              복사
            </button>
          </div>
        ))}
      </div>
      <p className="settings-current-note">
        참조 중인 sidecar를 보존하려면 전체 삭제 대신 고아 캐시 확인/삭제 명령을 사용하세요. .scenario-extract-cache는 임시 추출 공간입니다.
      </p>
    </section>
  );
}

function PresetSettings({ settings, updateSetting }) {
  return (
    <section className="settings-card">
      <div className="mini-title">
        <Settings2 size={16} />
        Preset Settings
      </div>
      <label>제목</label>
      <input value={settings.title} onChange={(event) => updateSetting('title', event.target.value)} />
      <label>설명</label>
      <input value={settings.description} onChange={(event) => updateSetting('description', event.target.value)} />
      <div className="two-col">
        <label className="checkbox-line">
          <input
            type="checkbox"
            checked={settings.multi_file}
            onChange={(event) => updateSetting('multi_file', event.target.checked)}
          />
          multi_file
        </label>
        <label className="checkbox-line">
          <input
            type="checkbox"
            checked={settings.allow_invalid_dbids}
            onChange={(event) => updateSetting('allow_invalid_dbids', event.target.checked)}
          />
          invalid DBID 허용
        </label>
      </div>
      {settings.multi_file && (
        <>
          <label>출력 폴더명</label>
          <input value={settings.out_name} onChange={(event) => updateSetting('out_name', event.target.value)} />
        </>
      )}
    </section>
  );
}

function CompanionGuide() {
  return (
    <details className="side-help-card companion-guide-card">
      <summary>
        <span>Companion Workflow</span>
        <strong>CMO 내부 UI를 기준으로 편집</strong>
      </summary>
      <ol className="workflow-list">
        <li>CMO에서 RP, Zone, Unit, Mission 위치와 이름을 먼저 만든다.</li>
        <li>Database Viewer에서 현재 DB 버전, DBID, Loadout ID를 확인한다.</li>
        <li>배치된 유닛은 우클릭 후 Scenario Editor의 Copy unit ID to clipboard로 GUID를 확보한다.</li>
        <li>Event Editor 또는 Lua Script Console의 Lua를 복사해 Assistant에 붙여넣는다.</li>
        <li>Assistant가 API, 트리거, DB/ID 위험 신호, 객체 이름 힌트를 분석한다.</li>
        <li>수정된 paste-ready Lua를 CMO 내부 Editor에 다시 붙여넣는다.</li>
      </ol>
    </details>
  );
}

function CmoPreparationChecklist() {
  return (
    <details className="side-help-card cmo-prep-card">
      <summary>
        <span>Before Building</span>
        <strong>CMO 준비 체크리스트</strong>
      </summary>
      <ul className="assistant-hint-list">
        <li>Side, Mission, Unit, RP, Zone 이름은 CMO 내부 UI에서 만든 실제 이름을 사용합니다.</li>
        <li>DBID/Loadout ID는 현재 시나리오 DB 기준으로 Database Viewer에서 확인합니다.</li>
        <li>배치된 유닛 조작은 가능하면 우클릭 메뉴의 Copy unit ID to clipboard GUID를 사용합니다.</li>
        <li>웹 도구는 지도/RP를 새로 만드는 곳이 아니라, CMO 내부 객체명과 Lua 논리를 보조하는 곳으로 사용합니다.</li>
      </ul>
    </details>
  );
}

function AssistantInsertPalette({ settings, requestLuaInsert }) {
  const [customPresets] = useState(readAssistantCustomPresets);

  const insertText = (label, output) => {
    if (!window.confirm(`${label}\n\n본문에 내용을 추가하겠습니까?`)) return;
    requestLuaInsert(output, label);
  };

  const insertTemplate = (kind) => {
    const template = getTemplateDefinition(kind);
    const event = createEventFromTemplate(kind);
    const output = generatePresetLua([event], {
      ...settings,
      title: `${template.title} preset`,
      description: template.summary || settings.description,
    });
    insertText(template.title, output);
  };

  const insertPreset = (preset) => {
    const output = generatePresetLua(preset.events, { ...settings, ...(preset.settings || {}) });
    insertText(preset.name || 'Custom preset', output);
  };

  return (
    <section className="assistant-insert-palette">
      <div className="mini-title">
        <BookOpen size={16} />
        템플릿 / 프리셋 삽입
      </div>
      <p className="palette-intro">
        그룹을 펼쳐 버튼을 누르면 Lua 분석 편집기 본문에 템플릿 Lua가 추가됩니다. 기존 내용은 유지되고, 작성된 내용 아래에 이어 붙습니다.
      </p>
      <div className="assistant-insert-groups">
        {FEATURE_FORM_GROUPS.map((group) => (
          <details key={group.name} className="assistant-insert-group">
            <summary>
              <span>{group.name}</span>
              <small>{group.forms.length}</small>
            </summary>
            <p>{group.description}</p>
            <div className="assistant-insert-buttons">
              {group.forms.map((kind) => {
                const template = getTemplateDefinition(kind);
                return (
                  <button key={kind} type="button" onClick={() => insertTemplate(kind)}>
                    + {template.title}
                  </button>
                );
              })}
            </div>
          </details>
        ))}
      </div>

      <div className="assistant-custom-presets">
        <strong>사용자 지정 프리셋</strong>
        <p>Preset Guide에서 저장한 사용자 지정 프리셋을 여기에서 Lua 본문으로 호출합니다.</p>
        {customPresets.length ? (
          <div className="assistant-insert-buttons">
            {customPresets.map((preset) => (
              <button key={preset.id || preset.name} type="button" onClick={() => insertPreset(preset)}>
                + {preset.name || 'Custom preset'}
              </button>
            ))}
          </div>
        ) : (
          <p>저장한 사용자 프리셋이 아직 없습니다.</p>
        )}
      </div>
    </section>
  );
}

function SidePane({ activeTab, settings, updateSetting, addBuilderForm, requestLuaInsert }) {
  if (activeTab === 'settings') {
    return (
      <div className="pane-stack">
        <CompanionGuide />
        <CmoPreparationChecklist />
      </div>
    );
  }

  if (activeTab === 'assistant') {
    return (
      <div className="pane-stack">
        <CompanionGuide />
        <CmoPreparationChecklist />
        <AssistantInsertPalette settings={settings} requestLuaInsert={requestLuaInsert} />
      </div>
    );
  }

  if (activeTab === 'guide') {
    return (
      <div className="pane-stack">
        <CompanionGuide />
        <CmoPreparationChecklist />
        <FeaturePalette onAddTemplate={addBuilderForm} />
      </div>
    );
  }

  return (
    <div className="pane-stack">
      <PresetSettings settings={settings} updateSetting={updateSetting} />
      <CmoPreparationChecklist />
      <FeaturePalette onAddTemplate={addBuilderForm} />
    </div>
  );
}

function App() {
  const [initialWorkspaceState] = useState(getInitialWorkspaceState);
  const [events, setEvents] = useState(initialWorkspaceState.events);
  const [activeTab, setActiveTab] = useState(initialWorkspaceState.activeTab);
  const [sidePaneWidth, setSidePaneWidth] = useState(initialWorkspaceState.sidePaneWidth);
  const [theme, setTheme] = useState(getInitialTheme);
  const [editorSettings, setEditorSettings] = useState(getInitialEditorSettings);
  const [availableEditorFonts, setAvailableEditorFonts] = useState(getAvailableEditorFonts);
  const [settings, setSettings] = useState(initialWorkspaceState.settings);
  const [guidePanel, setGuidePanel] = useState('encyclopedia');

  const addEvent = (kind = 'iads_ambush', overrides = {}) => {
    const nextEvent = createEventFromTemplate(kind, overrides);
    setEvents((current) => [...current, nextEvent]);
    return nextEvent;
  };

  const addBuilderForm = (kind = 'iads_ambush') => {
    const nextEvent = addEvent(kind);
    setGuidePanel('builder');
    setActiveTab('guide');
    return nextEvent;
  };

  const requestLuaInsert = (content, label) => {
    setActiveTab('assistant');
    window.dispatchEvent(new CustomEvent('cmo-lua-insert-request', {
      detail: {
        label,
        content,
      },
    }));
  };

  const updateEvent = (id, updatedEvent) => {
    setEvents((current) => current.map((event) => (event.id === id ? { ...event, ...updatedEvent } : event)));
  };

  const replaceEvent = (id, nextEvent) => {
    setEvents((current) => current.map((event) => (event.id === id ? nextEvent : event)));
  };

  const removeEvent = (id) => {
    setEvents((current) => current.filter((event) => event.id !== id));
  };

  const applyCustomPreset = ({ events: presetEvents, settings: presetSettings }) => {
    if (Array.isArray(presetEvents) && presetEvents.length) {
      setEvents(presetEvents);
    }

    if (presetSettings) {
      setSettings((current) => ({ ...current, ...presetSettings }));
    }
  };

  const updateSetting = (field, value) => {
    setSettings((current) => ({ ...current, [field]: value }));
  };

  const updateEditorSetting = (field, value) => {
    setEditorSettings((current) => ({ ...current, [field]: value }));
  };

  useEffect(() => {
    window.localStorage.setItem(THEME_STORAGE_KEY, theme);
  }, [theme]);

  useEffect(() => {
    window.localStorage.setItem(EDITOR_SETTINGS_STORAGE_KEY, JSON.stringify(editorSettings));
  }, [editorSettings]);

  useEffect(() => {
    window.localStorage.setItem(WORKSPACE_STATE_STORAGE_KEY, JSON.stringify({
      version: 1,
      savedAt: new Date().toISOString(),
      events,
      activeTab,
      sidePaneWidth,
      settings,
    }));
  }, [events, activeTab, sidePaneWidth, settings]);

  useEffect(() => {
    const persistWorkspaceState = () => {
      window.localStorage.setItem(WORKSPACE_STATE_STORAGE_KEY, JSON.stringify({
        version: 1,
        savedAt: new Date().toISOString(),
        events,
        activeTab,
        sidePaneWidth,
        settings,
      }));
    };

    window.addEventListener('pagehide', persistWorkspaceState);
    window.addEventListener('beforeunload', persistWorkspaceState);

    return () => {
      window.removeEventListener('pagehide', persistWorkspaceState);
      window.removeEventListener('beforeunload', persistWorkspaceState);
    };
  }, [events, activeTab, sidePaneWidth, settings]);

  useEffect(() => {
    let cancelled = false;

    const detectAvailableFonts = () => {
      const nextFonts = getAvailableEditorFonts();

      if (cancelled) return;

      setAvailableEditorFonts(nextFonts);
      setEditorSettings((current) => (
        nextFonts.some((option) => option.id === current.fontFamily)
          ? current
          : { ...current, fontFamily: nextFonts[0].id }
      ));
    };

    detectAvailableFonts();
    document.fonts?.ready?.then(detectAvailableFonts);

    return () => {
      cancelled = true;
    };
  }, []);

  const startResize = (event) => {
    const startX = event.clientX;
    const startWidth = sidePaneWidth;

    const handleMove = (moveEvent) => {
      const nextWidth = startWidth + (moveEvent.clientX - startX);
      setSidePaneWidth(Math.min(Math.max(nextWidth, 300), 680));
    };

    const stopResize = () => {
      window.removeEventListener('pointermove', handleMove);
      window.removeEventListener('pointerup', stopResize);
    };

    window.addEventListener('pointermove', handleMove);
    window.addEventListener('pointerup', stopResize);
  };

  const selectedEditorFont = availableEditorFonts.find((option) => option.id === editorSettings.fontFamily)
    || availableEditorFonts[0]
    || EDITOR_FONT_OPTIONS[0];

  return (
    <div
      id="app-container"
      data-theme={theme}
      style={{
        '--lua-editor-font-family': selectedEditorFont.value,
        '--lua-editor-font-size': `${editorSettings.fontSize}px`,
      }}
    >
      <header className="app-topbar glass-panel">
        <div className="brand-block">
          <div className="brand-copy">
            <p className="eyebrow">CMO Lua Builder</p>
            <h1>Mission Script Companion</h1>
          </div>
        </div>
        <nav className="workspace-tabs" aria-label="CMO Lua workspace tabs">
          {WORKSPACE_TABS.map((tab) => {
            const Icon = tab.icon;
            return (
              <button
                key={tab.id}
                className={`workspace-tab ${activeTab === tab.id ? 'active' : ''}`}
                type="button"
                onClick={() => setActiveTab(tab.id)}
              >
                <Icon size={16} />
                <span>{tab.label}</span>
                <small>{tab.hint}</small>
              </button>
            );
          })}
        </nav>
        <div className="topbar-spacer" aria-hidden="true" />
      </header>

      <main className="workspace-shell" style={{ '--side-pane-width': `${sidePaneWidth}px` }}>
        <aside className="workspace-side glass-panel">
          <SidePane
            activeTab={activeTab}
            settings={settings}
            updateSetting={updateSetting}
            addBuilderForm={addBuilderForm}
            requestLuaInsert={requestLuaInsert}
          />
        </aside>
        <button
          className="resize-handle"
          type="button"
          aria-label="보조 패널 폭 조절"
          onPointerDown={startResize}
        />
        <section className="workspace-primary">
          <div className="workspace-panel" hidden={activeTab !== 'assistant'}>
            <LuaAssistant />
          </div>
          <div className="workspace-panel" hidden={activeTab !== 'guide'}>
            <Suspense fallback={<div className="glass-panel preset-guide-loading">Loading Preset Guide...</div>}>
              <PresetGuide
                events={events}
                settings={settings}
                addEvent={addEvent}
                updateEvent={updateEvent}
                replaceEvent={replaceEvent}
                removeEvent={removeEvent}
                applyCustomPreset={applyCustomPreset}
                activePanel={guidePanel}
                setActivePanel={setGuidePanel}
              />
            </Suspense>
          </div>
          <div className="workspace-panel" hidden={activeTab !== 'settings'}>
            <AppSettingsWorkspace
              theme={theme}
              setTheme={setTheme}
              editorSettings={editorSettings}
              updateEditorSetting={updateEditorSetting}
              availableEditorFonts={availableEditorFonts}
              detectedFontCount={EDITOR_FONT_OPTIONS.length}
              settings={settings}
              updateSetting={updateSetting}
            />
          </div>
        </section>
      </main>
    </div>
  );
}

export default App;
